version: '3.4'

services: 

  frontend:
    image: productfrontend
    build:
      context: frontend
      dockerfile: Dockerfile
    environment: 
      - backendUrl=http://backend
    ports:
      - "5902:8080"
    depends_on: 
      - backend
  backend:
    image: productbackend
    build: 
      context: backend
      dockerfile: Dockerfile
    ports: 
      - "5200:8080"
    